#!/bin/tcsh

#PBS -m abe
#PBS -N ddf-rerun
#PBS -l nodes=1:ppn=32:lofar
#PBS -l walltime=72:00:00
#PBS -k oe
#PBS -q lofar
#PBS -W group_list=lofar

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

echo Working directory is $WD

cd $WD
bash -c /home/mjh/pipeline-master/ddf-pipeline/torque/rerun.sh
