#!/bin/tcsh

#PBS -m abe
#PBS -N vlow_reprocess
#PBS -l nodes=1:ppn=32
#PBS -l walltime=12:00:00
#PBS -k oe
#PBS -q main

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

echo Field is $FIELD

/soft/bin/singularity exec -B/home,/beegfs,/soft /data/lofar/mjh/test_sandbox2 /home/mjh/pipeline-py3/ddf-pipeline/torque/vlow_image.sh
